version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./languages/.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./languages/.env
    ports:
      - "5050:80"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  languages:
    image: snig501:languages
    env_file:
      - ./languages/.env
    build:
      context: ./
      dockerfile: ./languages/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  authenticator:
    image: snig501:authenticator
    env_file:
      - ./authenticator/.env
    build:
      context: ./
      dockerfile: ./authenticator/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
volumes:
  postgresDB:
  redis:
    driver: local
