import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * Represents a statement entity in the database.
 * A statement is a piece of text that has been translated and stored with relevant metadata.
 */
@Entity('statements')
export class Statement {
  /**
   * Unique identifier for each statement.
   * This is automatically generated by the database.
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The actual statement text (e.g., a sentence or phrase).
   * This field is required and has a maximum length of 2000 characters.
   */
  @Column({ name: 'statement', nullable: false, length: 2000 })
  statement: string;

  /**
   * The language in which the statement is written.
   * This field is required.
   */
  @Column({ name: 'language', nullable: false })
  language: string;

  /**
   * The timestamp when the statement was created or recorded.
   * This field is required.
   */
  @Column({ name: 'timestamp', nullable: false, type: 'timestamp' })
  timestamp: Date;

  /**
   * The source from which the statement originated (e.g., manual input, system-generated).
   * This field is required with a maximum length of 15 characters.
   */
  @Column({ name: 'source', nullable: false, length: 15 })
  source: string;

  /**
   * The unique identifier of the client who submitted or interacted with the statement.
   * This field is required.
   */
  @Column({
    name: 'clientId',
    nullable: false,
  })
  clientId: string;
}
